supported_accounts:
  # Below is a comprehensive list of the supported source accounts along 
  # with their corresponding columns. The columns are based on the default
  # download method and represent the structure of the downloaded raw 
  # transaction files. In the event that the financial company modifies 
  # the format of the downloaded files, a new item will be appended to
  # this list, denoting the year in which the change took place and increment
  # of that change (in the same year). This ensures that the application
  # remains adaptable to evolving file formats.

  # *** FORMAT : <account_name>_<format_year>_<format_increment>
  # e.g. citi_double_cash_2022_1 for a published format for the citi double
  # cash card in 2022.
  citi_double_cash_2022_1:
    - Status
    - Date
    - Description
    - Debit
    - Credit
  citi_custom_cash_2022_1:
    - Status
    - Date
    - Description
    - Debit
    - Credit
  amex_blue_cash_preferred_2022_1:
    - Date
    - Description
    - Card Member
    - "Account #"
    - Amount
  chase_freedom_unlimited_2022_1:
    - Transaction Date
    - Post Date
    - Description
    - Category
    - Type
    - Amount
    - Memo
  chase_amazon_visa_2022_1:
    - Transaction Date
    - Post Date
    - Description
    - Category
    - Type
    - Amount
    - Memo
  chase_debit_2022_1:
    - Details
    - Posting Date
    - Description
    - Amount
    - Type
    - Balance
    - "Check or Slip #"
  amazon_2023_1:
    - order id
    - items
    - to
    - date
    - total
    - shipping
    - shipping_refund
    - gift
    - tax
    - refund
    - payments
